const MIN = 50, MAX = 10000;
const isProduction = env => env.ECPAY_ENV === "production";
const endpoint = env => isProduction(env) ? "https://payment.ecpay.com.tw/Cashier/AioCheckOut/V5" : "https://payment-stage.ecpay.com.tw/Cashier/AioCheckOut/V5";
const cors = env => ({"Access-Control-Allow-Origin":env.PUBLIC_SITE_ORIGIN,"Access-Control-Allow-Methods":"POST, GET, OPTIONS","Access-Control-Allow-Headers":"Content-Type","Vary":"Origin"});
const reply = (data, status, env) => new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json",...cors(env)}});
function ecpayEncode(value){return encodeURIComponent(value).replace(/%20/g,"+").replace(/~/g,"%7E").replace(/'/g,"%27").toLowerCase().replace(/%2d/g,"-").replace(/%5f/g,"_").replace(/%2e/g,".").replace(/%21/g,"!").replace(/%2a/g,"*").replace(/%28/g,"(").replace(/%29/g,")")}
function ecpaySort(a,b){const left=a.toLowerCase(),right=b.toLowerCase();return left<right?-1:left>right?1:a<b?-1:a>b?1:0}
async function mac(params,env){const raw=Object.keys(params).filter(k=>k!=="CheckMacValue").sort(ecpaySort).map(k=>`${k}=${params[k]}`).join("&");const value=`HashKey=${env.ECPAY_HASH_KEY}&${raw}&HashIV=${env.ECPAY_HASH_IV}`;const bytes=new TextEncoder().encode(ecpayEncode(value));const hash=await crypto.subtle.digest("SHA-256",bytes);return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,"0")).join("").toUpperCase()}
function validAmount(value){return Number.isInteger(value)&&value>=MIN&&value<=MAX}
function id(){return "yf"+Date.now().toString(36)+crypto.getRandomValues(new Uint32Array(1))[0].toString(36)}
function date(){const d=new Date();return `${d.getFullYear()}/${String(d.getMonth()+1).padStart(2,"0")}/${String(d.getDate()).padStart(2,"0")} ${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}:${String(d.getSeconds()).padStart(2,"0")}`}
export default {async fetch(req,env){const url=new URL(req.url);if(req.method==="OPTIONS")return new Response(null,{headers:cors(env)});if(!env.ECPAY_MERCHANT_ID||!env.ECPAY_HASH_KEY||!env.ECPAY_HASH_IV)return reply({error:"payment service not configured"},503,env);
if(req.method==="POST"&&url.pathname==="/api/payment/create"){if(req.headers.get("origin")!==env.PUBLIC_SITE_ORIGIN)return reply({error:"forbidden"},403,env);if(!req.headers.get("content-type")?.includes("application/json"))return reply({error:"content type"},415,env);let body;try{body=await req.json()}catch{return reply({error:"invalid json"},400,env)}if(!validAmount(body.amount))return reply({error:"amount must be an integer from 50 to 10000"},400,env);const orderId=id(),tradeNo=("YF"+orderId).slice(0,20),origin=env.PUBLIC_SITE_ORIGIN;await env.DB.prepare("INSERT INTO orders(order_id,merchant_trade_no,amount,created_at) VALUES(?,?,?,?)").bind(orderId,tradeNo,body.amount,new Date().toISOString()).run();const params={MerchantID:env.ECPAY_MERCHANT_ID,MerchantTradeNo:tradeNo,MerchantTradeDate:date(),PaymentType:"aio",TotalAmount:body.amount,TradeDesc:"yifly sponsorship",ItemName:"yifly voluntary sponsorship",ReturnURL:`${url.origin}/api/payment/callback`,OrderResultURL:`${url.origin}/api/payment/result`,ClientBackURL:`${origin}/yifly/support.html`,ChoosePayment:"Credit",EncryptType:1,NeedExtraPaidInfo:"Y"};params.CheckMacValue=await mac(params,env);return reply({action:endpoint(env),params,orderId},200,env)}
if(req.method==="POST"&&url.pathname==="/api/payment/callback"){const form=Object.fromEntries(await req.formData());const receivedMac=String(form.CheckMacValue||"");const calculatedMac=await mac(form,env);const order=await env.DB.prepare("SELECT * FROM orders WHERE merchant_trade_no=?").bind(form.MerchantTradeNo||"").first();const logMeta={merchantTradeNo:form.MerchantTradeNo||null};console.log("callback received",logMeta);
if(receivedMac!==calculatedMac){console.error("callback rejected: checkmac mismatch",logMeta);return new Response("0|Error",{status:400,headers:{"content-type":"text/plain; charset=utf-8"}})}
if(form.MerchantID!==env.ECPAY_MERCHANT_ID){console.error("callback rejected: merchant mismatch",logMeta);return new Response("0|Error",{status:400,headers:{"content-type":"text/plain; charset=utf-8"}})}
if(!order){console.error("callback rejected: order not found",logMeta);return new Response("0|Error",{status:404,headers:{"content-type":"text/plain; charset=utf-8"}})}
if(Number(form.TradeAmt)!==order.amount){console.error("callback rejected: amount mismatch",logMeta);return new Response("0|Error",{status:400,headers:{"content-type":"text/plain; charset=utf-8"}})}
if(form.RtnCode!=="1"){console.error("callback rejected: rtn code not 1",logMeta);if(order.status==="pending")await env.DB.prepare("UPDATE orders SET status='failed',rtn_code=? WHERE merchant_trade_no=?").bind(form.RtnCode||null,order.merchant_trade_no).run();return new Response("1|OK",{headers:{"content-type":"text/plain; charset=utf-8"}})}
if(isProduction(env)&&form.SimulatePaid==="1"){console.error("callback rejected: simulated payment in production",logMeta);return new Response("0|Error",{status:400,headers:{"content-type":"text/plain; charset=utf-8"}})}
console.log("callback verified",logMeta);if(order.status!=="paid"){await env.DB.prepare("UPDATE orders SET status='paid',paid_at=?,trade_no=?,payment_type=?,rtn_code=? WHERE merchant_trade_no=?").bind(new Date().toISOString(),form.TradeNo||null,form.PaymentType||null,form.RtnCode,order.merchant_trade_no).run();console.log("order updated to paid",{merchantTradeNo:order.merchant_trade_no})}else console.log("callback already processed",{merchantTradeNo:order.merchant_trade_no});return new Response("1|OK",{headers:{"content-type":"text/plain; charset=utf-8"}})}
if(req.method==="POST"&&url.pathname==="/api/payment/result"){const form=Object.fromEntries(await req.formData());const order=await env.DB.prepare("SELECT order_id FROM orders WHERE merchant_trade_no=?").bind(form.MerchantTradeNo||"").first();const idForStatus=order?.order_id||form.MerchantTradeNo||"";return Response.redirect(`${env.PUBLIC_SITE_ORIGIN}/yifly/support-success.html?orderId=${encodeURIComponent(idForStatus)}`,303)}
const match=url.pathname.match(/^\/api\/payment\/status\/([A-Za-z0-9]+)$/);if(req.method==="GET"&&match){const order=await env.DB.prepare("SELECT status FROM orders WHERE order_id=? OR merchant_trade_no=?").bind(match[1],match[1]).first();return order?reply({status:order.status},200,env):reply({error:"not found"},404,env)}return new Response("Not found",{status:404})}}
